name = "Sbplib"
uuid = "5a373a26-915f-4769-bcab-bf03835de17b"
authors = ["Jonatan Werpers <jonatan@werpers.com>", "Vidar Stiernström <vidar.stiernstrom@it.uu.se>, and contributors"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
TiledIteration = "06e1c1a7-607b-532d-9fad-de7d9aa2abac"

[weakdeps]
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[extensions]
SbplibMakieExt = "Makie"
SbplibPlotsExt = "Plots"

[compat]
julia = "1.5"
