name = "Grids"
uuid = "960fdf28-97ed-11e9-2a74-bd90bf2fab5a"
authors = ["Jonatan Werpers <jonatan.werpers@it.uu.se>"]
version = "0.1.0"

[deps]
RegionIndices = "5d527584-97f1-11e9-084c-4540c7ecf219"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
